spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:scraping}
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:scraping}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  mail:
    # host: ${MAIL_HOST:localhost}
    host: ${MAIL_HOST:mail}
    port: ${MAIL_PORT:1025}
  batch:
    jdbc:
      initialize-schema: always

